/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UsainSprintPages.Manager;

import Controller.Manager.CreateMenuItemController;
import Controller.Manager.DeleteMenuItemController;
import Controller.Manager.ModifyMenuItemController;
import Controller.Manager.ViewMenuItemController;
import UsainSprintPages.UserAdmin.LoginPage;
import java.awt.Dimension;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.FoodItem;

/**
 *
 * @author Eechang
 */
public class ManagerManageFoodItemPage extends javax.swing.JFrame {

    private static final int JF_W=1353;
    private  static final int JF_H =710;
    public Dimension getPreferredSize()
    {
        return new Dimension(JF_W, JF_H);
    }
    /**
     * Creates new form ManagerManageFoodItemPage
     */
    public ManagerManageFoodItemPage() {
        initComponents();
        btnCreate.setEnabled(false);
        btnModify.setEnabled(false);
        btnClear.setEnabled(false);
        btnDelete.setEnabled(false);
        
        lblFoodItemNameExist.setVisible(false);
    }

    public ManagerManageFoodItemPage(String name) {
        initComponents();
        Sname.setText(name);
        btnCreate.setEnabled(false);
        btnModify.setEnabled(false);
        btnClear.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    public void clear() {
        txtFoodItemName.setText("");
        txtCategory.setText("");
        txtFoodItemPrice.setText("");
        txtFoodItemDescription.setText("");
        txtFoodItemAllergens.setText("");
        lblFoodItemNameExist.setVisible(false);
         btnCreate.setEnabled(false);
        btnModify.setEnabled(false);
        btnClear.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    public void validateFields() {
        String FoodItemName = txtFoodItemName.getText();
        String FoodItemPrice = txtCategory.getText();
        String FoodItemDescription = txtFoodItemDescription.getText();
        if (!FoodItemName.equals("") && (!FoodItemPrice.equals("")) && (!FoodItemDescription.equals(""))) {
            btnCreate.setEnabled(true);
        } else {
            btnCreate.setEnabled(false);
        }
        if (!FoodItemName.equals("") && (!FoodItemPrice.equals("")) && (!FoodItemDescription.equals(""))) {
            btnModify.setEnabled(true);
        } else {
            btnModify.setEnabled(false);
        }
        if (!FoodItemName.equals("") && (!FoodItemPrice.equals("")) && (!FoodItemDescription.equals(""))) {
            btnClear.setEnabled(true);
        } else {
            btnClear.setEnabled(false);
        }
        if (!FoodItemName.equals("") && (!FoodItemPrice.equals("")) && (!FoodItemDescription.equals(""))) {
            btnDelete.setEnabled(true);
        } else {
            btnDelete.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoodCategoryExist = new javax.swing.JLabel();
        lblFoodCategoryExist1 = new javax.swing.JLabel();
        lblFoodCategoryExist2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        Sname = new javax.swing.JLabel();
        btnCoupon = new javax.swing.JButton();
        btnFoodItem = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSearchFoodItemName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtFoodItemName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFoodItemDescription = new javax.swing.JTextArea();
        txtFoodItemAllergens = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblFoodItemId = new javax.swing.JLabel();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblFoodItemNameExist = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtFoodItemPrice = new javax.swing.JTextField();

        lblFoodCategoryExist.setForeground(new java.awt.Color(255, 0, 0));
        lblFoodCategoryExist.setText("Food category already exists");

        lblFoodCategoryExist1.setForeground(new java.awt.Color(255, 0, 0));
        lblFoodCategoryExist1.setText("Food category already exists");

        lblFoodCategoryExist2.setForeground(new java.awt.Color(255, 0, 0));
        lblFoodCategoryExist2.setText("Food category already exists");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1353, 710));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 31, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, 10));

        jLabel11.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hello");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 60, 40));

        Sname.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 18)); // NOI18N
        Sname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 80, 40));

        btnCoupon.setBackground(new java.awt.Color(0, 31, 125));
        btnCoupon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCoupon.setForeground(new java.awt.Color(255, 255, 255));
        btnCoupon.setText("Coupon");
        btnCoupon.setBorder(null);
        btnCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCouponActionPerformed(evt);
            }
        });
        jPanel1.add(btnCoupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 45));

        btnFoodItem.setBackground(new java.awt.Color(44, 115, 210));
        btnFoodItem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFoodItem.setForeground(new java.awt.Color(255, 255, 255));
        btnFoodItem.setText("Food Item");
        btnFoodItem.setBorder(null);
        btnFoodItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodItemActionPerformed(evt);
            }
        });
        jPanel1.add(btnFoodItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, 45));

        btnLogout.setBackground(new java.awt.Color(0, 31, 125));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log out");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 200, 45));

        jLabel19.setFont(new java.awt.Font("Academy Engraved LET", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Usain Sprint");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 710));

        jPanel2.setBackground(new java.awt.Color(0, 115, 189));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        jLabel7.setText("Search  :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 40));

        txtSearchFoodItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFoodItemNameActionPerformed(evt);
            }
        });
        txtSearchFoodItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchFoodItemNameKeyReleased(evt);
            }
        });
        jPanel2.add(txtSearchFoodItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 150, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1160, 100));

        jPanel3.setBackground(new java.awt.Color(0, 152, 196));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFoodItemName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFoodItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoodItemNameActionPerformed(evt);
            }
        });
        txtFoodItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFoodItemNameKeyReleased(evt);
            }
        });
        jPanel3.add(txtFoodItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 210, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Food Item Name :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 40));

        txtCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCategoryKeyReleased(evt);
            }
        });
        jPanel3.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 210, 30));

        txtFoodItemDescription.setColumns(20);
        txtFoodItemDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFoodItemDescription.setRows(5);
        txtFoodItemDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFoodItemDescriptionKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtFoodItemDescription);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 220, 100));

        txtFoodItemAllergens.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFoodItemAllergens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFoodItemAllergensKeyReleased(evt);
            }
        });
        jPanel3.add(txtFoodItemAllergens, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 220, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Category :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Allergens :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Food Item ID :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 30));

        lblFoodItemId.setBackground(new java.awt.Color(255, 255, 255));
        lblFoodItemId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFoodItemId.setForeground(new java.awt.Color(255, 255, 255));
        lblFoodItemId.setText("00");
        jPanel3.add(lblFoodItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 50, 30));

        btnModify.setBackground(new java.awt.Color(69, 221, 186));
        btnModify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        jPanel3.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 110, 40));

        btnDelete.setBackground(new java.awt.Color(69, 221, 186));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 110, 40));

        btnClear.setBackground(new java.awt.Color(69, 221, 186));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 110, 40));

        btnCreate.setBackground(new java.awt.Color(69, 221, 186));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel3.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 110, 40));

        lblFoodItemNameExist.setForeground(new java.awt.Color(153, 0, 51));
        lblFoodItemNameExist.setText("Food item name already exists");
        jPanel3.add(lblFoodItemNameExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 210, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("*Click on row to select");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Price", "Description", "Allergen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 570, 490));

        txtFoodItemPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFoodItemPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFoodItemPriceKeyReleased(evt);
            }
        });
        jPanel3.add(txtFoodItemPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 210, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 1160, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFoodItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoodItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoodItemNameActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnFoodItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodItemActionPerformed
        // TODO add your handling code here:
        String ShowName = Sname.getText();
        new ManagerManageFoodItemPage(ShowName).setVisible(true);
    }//GEN-LAST:event_btnFoodItemActionPerformed

    private void txtSearchFoodItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFoodItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFoodItemNameActionPerformed

    private void txtFoodItemNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoodItemNameKeyReleased
        lblFoodItemNameExist.setVisible(false);
        validateFields();
        CreateMenuItemController Fit = new CreateMenuItemController();
        Fit.FitemName = txtFoodItemName.getText();
        
        if (Fit.CheckFoodName()) {
           btnCreate.setEnabled(false);
            btnModify.setEnabled(false);
            btnDelete.setEnabled(false);
            lblFoodItemNameExist.setVisible(true);
        }
         
    }//GEN-LAST:event_txtFoodItemNameKeyReleased

    private void txtCategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoryKeyReleased
        validateFields();
    }//GEN-LAST:event_txtCategoryKeyReleased

    private void txtFoodItemDescriptionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoodItemDescriptionKeyReleased
        validateFields();
    }//GEN-LAST:event_txtFoodItemDescriptionKeyReleased

    private void txtFoodItemAllergensKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoodItemAllergensKeyReleased
        validateFields();
    }//GEN-LAST:event_txtFoodItemAllergensKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        Iterator<FoodItem> itr2 = ViewMenuItemController.getFoodData();
        while (itr2.hasNext()) {
            FoodItem foodItemObj = itr2.next();
            dtm.addRow(new Object[]{foodItemObj.getFoodItemId(), foodItemObj.getFoodItemName(), foodItemObj.getFoodItemCategory(), foodItemObj.getFoodItemPrice(), foodItemObj.getFoodItemDescription(), foodItemObj.getFoodItemAllergens()});
        }
    }//GEN-LAST:event_formComponentShown

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        CreateMenuItemController Cmc = new CreateMenuItemController();
        Cmc.FoodName = txtFoodItemName.getText();
        Cmc.CategoryName = txtCategory.getText();
        Cmc.FoodPrice = (Float.valueOf(txtFoodItemPrice.getText()));
        Cmc.Description = txtFoodItemDescription.getText();
        Cmc.Allergens = txtFoodItemAllergens.getText();
        Cmc.createFoodItemController();
        setVisible(false);
        new ManagerManageFoodItemPage().setVisible(true);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String FoodItemId = model.getValueAt(index, 0).toString();
        lblFoodItemId.setText(FoodItemId);
        String FoodItemName = model.getValueAt(index, 1).toString();
        txtFoodItemName.setText(FoodItemName);
        String FoodItemCategory = model.getValueAt(index, 2).toString();
        txtCategory.setText(FoodItemCategory);
        String FoodItemPrice = model.getValueAt(index, 3).toString();
        txtFoodItemPrice.setText(FoodItemPrice);
        String FoodItemDescription = model.getValueAt(index, 4).toString();
        txtFoodItemDescription.setText(FoodItemDescription);
        String FoodItemAllergens = model.getValueAt(index, 5).toString();
        txtFoodItemAllergens.setText(FoodItemAllergens);
        btnModify.setEnabled(true);
        btnDelete.setEnabled(true);
        btnClear.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
       
       ModifyMenuItemController Mii = new ModifyMenuItemController();
       int FoodItemIdNo = Integer.parseInt(lblFoodItemId.getText());
       Mii.FoodItemId = FoodItemIdNo;
       Mii.FoodItemName = txtFoodItemName.getText();
       Mii.FoodItemCategory =txtCategory.getText();
       Mii.FoodItemPrice = (Float.valueOf(txtFoodItemPrice.getText()));
       Mii.FoodItemDescription = txtFoodItemDescription.getText();
       Mii.FoodItemAllergens = txtFoodItemAllergens.getText();
       Mii.modifyMenuItemController();
       setVisible(false);
       new ManagerManageFoodItemPage().setVisible(true);
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete food item?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
        DeleteMenuItemController Dmi = new DeleteMenuItemController();
        Dmi.FoodName = txtFoodItemName.getText();
        Dmi.deleteFoodItemController();
        String ShowName = Sname.getText();
        setVisible(false);
        new ManagerManageFoodItemPage(ShowName).setVisible(true);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchFoodItemNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchFoodItemNameKeyReleased
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)"+ txtSearchFoodItemName.getText().trim(),1));
    }//GEN-LAST:event_txtSearchFoodItemNameKeyReleased

    private void btnCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCouponActionPerformed
        setVisible(false);
        String ShowName = Sname.getText();
        new ManagerManageCouponPage(ShowName).setVisible(true);
    }//GEN-LAST:event_btnCouponActionPerformed

    private void txtFoodItemPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFoodItemPriceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoodItemPriceKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerManageFoodItemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerManageFoodItemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerManageFoodItemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerManageFoodItemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new ManagerManageFoodItemPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sname;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCoupon;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFoodItem;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFoodCategoryExist;
    private javax.swing.JLabel lblFoodCategoryExist1;
    private javax.swing.JLabel lblFoodCategoryExist2;
    private javax.swing.JLabel lblFoodItemId;
    private javax.swing.JLabel lblFoodItemNameExist;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtFoodItemAllergens;
    private javax.swing.JTextArea txtFoodItemDescription;
    private javax.swing.JTextField txtFoodItemName;
    private javax.swing.JTextField txtFoodItemPrice;
    private javax.swing.JTextField txtSearchFoodItemName;
    // End of variables declaration//GEN-END:variables
}
