/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UsainSprintPages.Customer;

import Controller.Customer.ViewOrdersController;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.OrderDetails;


/**
 *
 * @author Eechang
 */
public class CustomerViewOrderPage extends javax.swing.JFrame {
    
    int sample =1000;
    public int orderId;
    
    private static final int JF_W=549;
    private  static final int JF_H =710;
    public Dimension getPreferredSize()
    {
        return new Dimension(JF_W, JF_H);
    }
    /**
     * Creates new form CustomerViewOrderPage
     */
    public CustomerViewOrderPage() {
        initComponents();
    }
    public CustomerViewOrderPage(int id, Float Gt,Float Discount,Float Total, String date) {
        initComponents();
        
        //orderId=id;
        orderId=id;
        TxtDate.setText(date);
        lblOrderID.setText(String.valueOf(orderId));
        TxtGTprice.setText(String.valueOf(Gt));
        TxtDiscount.setText(String.valueOf(Discount));
        TxtTotal.setText(String.valueOf(Total));
        myTimer.start();
    }
    Timer myTimer = new Timer(1000, new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
            ViewOrdersController Vbc = new ViewOrdersController();
            Vbc.StatuId=orderId;
            lblStatus.setText(Vbc.getOrderStatus());  
        }
        });
       
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblOrderID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TxtDate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxtGTprice = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JLabel();
        TxtDiscount = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        BtnExit = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(549, 710));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 150, 199));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrderID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("invoice NO. :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 30));

        jLabel2.setFont(new java.awt.Font("Trattatello", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Usain Sprint");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 160, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 340, 420));
        jPanel1.add(TxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Grand total price: $");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, -1, -1));

        TxtGTprice.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        TxtGTprice.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TxtGTprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 60, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total paid: $");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, -1, -1));

        TxtTotal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        TxtTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 70, 20));

        TxtDiscount.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        TxtDiscount.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TxtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 80, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Coupon discount: $");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, -1, 30));

        BtnExit.setBackground(new java.awt.Color(0, 150, 199));
        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, 70, 40));

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 100, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        Iterator<OrderDetails> itr =  ViewOrdersController.ViewBill(orderId);
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
         while (itr.hasNext()) {
                    OrderDetails OdObj = itr.next();
                    dtm.addRow(new Object[]{OdObj.getFoodItem(),OdObj.getFoodQuantity(),OdObj.getFoodPrice()});
         } 
            
       
    }//GEN-LAST:event_formComponentShown

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerFirstPage().setVisible(true);
    }//GEN-LAST:event_BtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerViewOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerViewOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerViewOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerViewOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new CustomerViewOrderPage().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JLabel TxtDate;
    private javax.swing.JLabel TxtDiscount;
    private javax.swing.JLabel TxtGTprice;
    private javax.swing.JLabel TxtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
