/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UsainSprintPages.Staff;

import Controller.Staff.CancelOrdersController;
import Controller.Staff.ViewOrdersController;
import Controller.Staff.ModifyOrdersController;
import UsainSprintPages.UserAdmin.LoginPage;
import java.awt.Dimension;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Orders;

/**
 *
 * @author Eechang
 */
public class StaffManageOrderPage extends javax.swing.JFrame {
    
    private static final int JF_W=1353;
    private  static final int JF_H =710;
    public Dimension getPreferredSize()
    {
        return new Dimension(JF_W, JF_H);
    }
    /**
     * Creates new form StaffManageOrderPage
     */
    public StaffManageOrderPage() {
        initComponents();
    }
    
    public StaffManageOrderPage(String SHowname) {
        initComponents();
        ShowNa.setText(SHowname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCancelOrder = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnFulfillOrder = new javax.swing.JButton();
        btnUnfulfillOrder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTableNumber = new java.awt.Label();
        lblOrderID = new java.awt.Label();
        lblStatus = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ShowNa = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSearchOrderID = new javax.swing.JTextField();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1353, 710));
        setSize(new java.awt.Dimension(10, 10));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Order ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 100, 30));

        btnCancelOrder.setBackground(new java.awt.Color(219, 13, 155));
        btnCancelOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 110, 40));

        jLabel8.setText("*Click on row to select");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 610, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Table No", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 580, 480));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Table Number:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 120, 30));

        btnFulfillOrder.setBackground(new java.awt.Color(13, 219, 131));
        btnFulfillOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFulfillOrder.setText("Fulfill Order");
        btnFulfillOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFulfillOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnFulfillOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 110, 40));

        btnUnfulfillOrder.setBackground(new java.awt.Color(255, 135, 15));
        btnUnfulfillOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUnfulfillOrder.setText("Unfulfill Order");
        btnUnfulfillOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnfulfillOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnfulfillOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Status:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 90, 40));

        lblTableNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTableNumber.setText("label1");
        getContentPane().add(lblTableNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 90, 50));

        lblOrderID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOrderID.setText("label2");
        getContentPane().add(lblOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 90, 50));

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatus.setText("label3");
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 140, 40));

        jPanel1.setBackground(new java.awt.Color(0, 31, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Academy Engraved LET", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Usain Sprint");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 190, 70));

        jLabel12.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hello");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 40));

        ShowNa.setFont(new java.awt.Font("YuMincho +36p Kana", 1, 18)); // NOI18N
        ShowNa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ShowNa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 10));

        btnLogout.setBackground(new java.awt.Color(0, 31, 125));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 190, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 710));

        jPanel2.setBackground(new java.awt.Color(0, 142, 155));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Search by order ID:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, 40));

        txtSearchOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchOrderIDActionPerformed(evt);
            }
        });
        txtSearchOrderID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchOrderIDKeyReleased(evt);
            }
        });
        jPanel2.add(txtSearchOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 230, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1170, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtSearchOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchOrderIDActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        CancelOrdersController Coc = new CancelOrdersController();
        Coc.Id = Integer.parseInt(lblTableNumber.getText());
        Coc.cancelOrderController();
        setVisible(false);
        new StaffManageOrderPage().setVisible(true);
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
         DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
           Iterator<Orders> itr=ViewOrdersController.getdata();
        while (itr.hasNext()) {
            Orders orderObj = itr.next();
            dtm.addRow(new Object[]{orderObj.getId(), orderObj.getTableNumber(), orderObj.getStatus()});
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        btnCancelOrder.setEnabled(true);
        btnFulfillOrder.setEnabled(true);
        btnUnfulfillOrder.setEnabled(true);
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        String tableNumber = model.getValueAt(index, 0).toString();
        lblTableNumber.setText(tableNumber);
        String orderId = model.getValueAt(index, 1).toString();
        lblOrderID.setText(orderId);
        String status = model.getValueAt(index, 2).toString();
        lblStatus.setText(status);
        if (status.equals("Unfulfilled"))
        {
            btnUnfulfillOrder.setEnabled(false);
        }
        else if (status.equals("Fulfilled"))
        {
            btnFulfillOrder.setEnabled(false);
        }
        else if(status.equals("Cancelled"))
        {
            btnCancelOrder.setEnabled(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtSearchOrderIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchOrderIDKeyReleased
     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();  
     
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)"+ txtSearchOrderID.getText().trim(),0));
    }//GEN-LAST:event_txtSearchOrderIDKeyReleased

    private void btnFulfillOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFulfillOrderActionPerformed
        ModifyOrdersController Moc = new ModifyOrdersController();
        Moc.Id = Integer.parseInt(lblTableNumber.getText());
        Moc.fulfillOrderController();
        setVisible(false);
        new StaffManageOrderPage().setVisible(true);
    }//GEN-LAST:event_btnFulfillOrderActionPerformed

    private void btnUnfulfillOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnfulfillOrderActionPerformed
        ModifyOrdersController Moc = new ModifyOrdersController();
        Moc.Id = Integer.parseInt(lblTableNumber.getText());
        Moc.unfulfillOrderController();
        setVisible(false);
        new StaffManageOrderPage().setVisible(true);
    }//GEN-LAST:event_btnUnfulfillOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffManageOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffManageOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffManageOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffManageOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new StaffManageOrderPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ShowNa;
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnFulfillOrder;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUnfulfillOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private java.awt.Label lblOrderID;
    private java.awt.Label lblStatus;
    private java.awt.Label lblTableNumber;
    private javax.swing.JTextField txtSearchOrderID;
    // End of variables declaration//GEN-END:variables
}
